import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { Box, Button, Text } from "@chakra-ui/react";
import ButtonRte from "@/components/button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SNews</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box
          display={"flex"}
          justifyContent={"space-between"}
          alignItems={"center"}
          className={styles.home_top__container}
        >
          <Box display={"flex"}>
            <Box marginRight={"23px"}>
              <Image
                src={"/assets/logo.svg"}
                alt={"123"}
                width={100}
                height={24}
              />
            </Box>
            <Box padding={"3px"}>
              <Text fontWeight={800} fontSize={"10px"} lineHeight={"12px"}>
                Thursday, June 03, 2023
              </Text>
              <Text fontSize={"10px"} fontWeight={"medium"} color={"black.300"}>
                Today’s paper
              </Text>
            </Box>
          </Box>
          <Box>
            <ButtonRte title="Login" />
          </Box>
        </Box>
      </main>
    </>
  );
}
